# R Tutorial
These are my notes for R. I learned R long ago and forgot a lot about how things work here. So here I created a klind of cheat sheet where I can look up to and see how things work. I hope this is useful to people as much as it is to me

In [52]:
#This is a comment
#Multiple line comments are not allowed
a <- 4
print(a)

[1] 4


### Variable assignment in R
* **a <- 5 or left assignment** is the proper way to define variables which means the value on right is assigned to the variable on the left 
* **a -> b or right assignment** can be used to give the value of a to be (given opebject b exists at all

* Instead of one ">" we can also use 2 ">" as in a<<-b . It is a convention in R to not use the = sign unless assigning for a function parameter

In [53]:
a <- TRUE  #T stands for True and F stands for False
class(a) #The fucntion tells us what data type the variable is in
b <- 23.4
class(b)
c <- 2L
class(c)
d<- 1+2i #Note it is not j like python
class(d)
e<- "The quick brown fox"
class(e)

[1] "logical"

[1] "numeric"

[1] "integer"

[1] "complex"

[1] "character"

### Data structures in R

In [66]:
#vectors- They contain a list of data of the same class
#c stands for combine
apple <- c('red','green',"yellow")
print(apple)

[1] "red"    "green"  "yellow"


In [55]:
#Vectors can contain only one type of data and lists can contain everything
list1 <- list(c(2,5,3),21.3,"Dog")
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
[1] "Dog"



In [56]:
#Matrix are 2 dimensional vectors
M = matrix( c('a','a','b','c','b','a'), nrow = 2, ncol = 3, byrow = TRUE)
# This is how the matrix function will work
M2= matrix( c(8,2,3,4,5,6,7,1,8,9,10), 3, 4)
print(M2)
#In case the data length is not equal to r*c, it will issue a warning and rotate the array elements

Warning message in matrix(c(8, 2, 3, 4, 5, 6, 7, 1, 8, 9, 10), 3, 4):
“data length [11] is not a sub-multiple or multiple of the number of rows [3]”

     [,1] [,2] [,3] [,4]
[1,]    8    4    7    9
[2,]    2    5    1   10
[3,]    3    6    8    8


In [57]:
#An N dimensional Matrix is called an Array 
# Create an array.
a <- array(c('green','yellow'),dim = c(3,3,2))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



In [58]:
#A less used data structure is a factor. It stores data like vectors but distinct values specefically 
a <- c(1,1,2,3,1,2,3,5,7,2,6,8,1,4,6,8)
a <- factor(a)
print(a)
cat ( "number of levels is" , nlevels(a) )
#Cat function is same as print function but it combines multiple inputs together so is more valid

 [1] 1 1 2 3 1 2 3 5 7 2 6 8 1 4 6 8
Levels: 1 2 3 4 5 6 7 8
number of levels is 8

In [59]:
# Create the data frame.
#This is similar to Pandas data fram in Python
BMI <- 	data.frame(
   gender = c("Male", "Male","Female"), 
   height = c(152, 171.5, 165), 
   weight = c(81,93, 78),
   Age = c(42,38,26)
)
print(BMI)

  gender height weight Age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


In [60]:
#Printing all variables that we have in this file
ls()
ls ( pattern= "e")

[1] "a"     "apple" "b"     "BMI"   "c"     "d"     "e"     "list1" "M"    
[10] "M2"

[1] "apple" "e"

In [61]:
rm ( a )
# Deletes one variable
rm ( list = ls() )
#Deletes a list of variables

### Arithmetic Operatios basics

In [69]:
a <- c(1,2,3)
b <- c(4,5,6)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%%b) #remainder
print(a %/% b) #integer quotients 
print(a^b)  #Power

[1] 5 7 9
[1] -3 -3 -3
[1]  4 10 18
[1] 0.25 0.40 0.50
[1] 1 2 3
[1] 0 0 0
[1]   1  32 729


#### The logical operators are more or less the same as everywhere else 
#### == != > >= < <= 

In [72]:
# Elementswise vs General logical operators 
a<- c(T,T,T,F,F,F)
b<- c(T,F,T,F,T,F)
a&b
a&&b # compares only first element
# sameway | vs || 
# Not for not

[1]  TRUE FALSE  TRUE FALSE FALSE FALSE

[1] TRUE

In [74]:
a<- c(1,2,3,4,5,6)
print (1 %in% a)
# This operator searches for an element in the vector

[1] TRUE


### Learning about if else, Loop and fucntions in R

In [4]:
if(2+3==5)
    {
    print("The truth prevails")
} else if(2==1){    #This needs to be in the same line. No newline or there is error
    print("Not really")
} else{
    print("Why are we even printing this")
}

[1] "The truth prevails"


In [11]:
# I don't really understand the absurdity of R switch functions. There is no default parameter. 
# You can do this
x<-3
#This goes of the form switch (expression, condition1, condition2, condition3, condition4) 
#The condition executes by index 
switch (x, "one", "two", "three")

[1] "three"

In [16]:
#Repeat loop, More like DO while but pretty dumb 
x<- 10
repeat{
    print(x)
    x<- x-1
    if(x==0){
        break
    }
}

[1] 10
[1] 9
[1] 8
[1] 7
[1] 6
[1] 5
[1] 4
[1] 3
[1] 2
[1] 1


In [21]:
for( i in seq(1,10)){
 print(i)   
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [23]:
i <- 1
while (i < 6) {
print(i)
i<- i+ 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [25]:
# Create a function 
new.function <- function(a=1,b,c) { #default arguements are allowed
   result <- a * b + c
   print(result)
}

# Call the function by position of arguments.
new.function(5,3,11)

# Call the function by names of the arguments.
new.function(a = 11, b = 5, c = 3)

[1] 26
[1] 58


#### Lazy Evaluation- The concept means that memeory is not immediately allocated for functional arguements as soon as they are specified. There are some functional arguements and they are assigned when they are needed so if there is a parameter that is not needed and it is not specified, ther won't be any error

### Strings, Vectors, Data structures 
**NB**: Array starts from 1

In [8]:
a<- "This is a string "
b<- "This is another strinng"
print(paste(a,b,sep="X"))  #Sep stands for seperator
nchar(a) #Number of characters in a string
substring(a,1,6) #Substring output

[1] "This is a string XThis is another strinng"


[1] 17

[1] "This i"

In [12]:
a <- seq(5,13,by=1) #By represents step size
a[c(2,3,6)] #Integer selction 
sort(a)  #This function is used to sort arrays
# We can do all scalar operations on 2 vectors

[1]  6  7 10

[1]  5  6  7  8  9 10 11 12 13

In [19]:
list1 <- list(1,2,3)
list2 <- list("Sun","Mon","Tue")
names(list2)<- c("one","two","three") #We can assign names to list elements like in python dictionaries
print(list2)
print(list2["one"])

$one
[1] "Sun"

$two
[1] "Mon"

$three
[1] "Tue"

$one
[1] "Sun"



### In case of matrixes, it is the same thing as lists but instead of list(), we use matrix(), to construct it
### Array is a matrix of n dimensions

In [20]:
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)
column_names <- c("COL1","COL2","COL3")
row_names <- c("ROW1","ROW2","ROW3")
matrix_names <- c("Matrix1","Matrix2")
result <- array(c(vector1,vector2),dim = c(3,3,2),dimnames = list(row_names,column_names,
   matrix_names))
print(result)

, , Matrix1

     COL1 COL2 COL3
ROW1    5   10   13
ROW2    9   11   14
ROW3    3   12   15

, , Matrix2

     COL1 COL2 COL3
ROW1    5   10   13
ROW2    9   11   14
ROW3    3   12   15



## Statistical Operations

In [22]:
x <- c(12,7,3,4.2,18,2,54,-21,8,-5)
mean(x)
median(x)
#mode is not a well defined dunction in R. We need to dind ourselves
#Mode

[1] 8.22

[1] 5.6

[1] "numeric"

### Reading CSV data

In [27]:
#Geting and setting directories
print(getwd())
setwd("~/")
print(getwd())

[1] "/home/brainsick/Documents"
[1] "/home/brainsick"


In [32]:
#Importing CSV
data <- read.csv("Data.csv") 
head(data) #Prints data head i.e. first 5 values 
tail(data) #Print data tail i.e. last 5 values

YearsExperience Salary
1 1.1             39343 
2 1.3             46205 
3 1.5             37731 
4 2.0             43525 
5 2.2             39891 
6 2.9             56642

YearsExperience Salary
25  8.7            109431
26  9.0            105582
27  9.5            116969
28  9.6            112635
29 10.3            122391
30 10.5            121872

In [33]:
nrow(data) #Number of rows
ncol(data) #Number of columns

[1] 30

[1] 2

In [38]:
is.data.frame(data) 
is.factor(data) #is.<insert_data_type> checks what kind of data it is

[1] TRUE

[1] FALSE

In [44]:
which.max(data$Salary) #Checks index of max salary 
max(data$Salary)  #Finds maximum salary

[1] 29

[1] 122391

In [51]:
#We can use as many queries to generate subsets
retval <- subset(data, Salary > 120000 & Salary!=0)
print(retval)

   YearsExperience Salary
29            10.3 122391
30            10.5 121872


In [54]:
#Dataframes can be written into CSVs as well 
write.csv(retval,"output.csv")
xxx<- read.csv("output.csv")
head(xxx)

X  YearsExperience Salary
1 29 10.3            122391
2 30 10.5            121872

### Installing and viewing packages

In [56]:
install.packages("xlsx") #To read Excel files

Installing package into ‘/home/brainsick/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘rJava’, ‘xlsxjars’



In [57]:
library(xlsx)